# Generated by Django 5.1.4 on 2024-12-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='max_inscripciones',
            field=models.IntegerField(default=1),
        ),
    ]
