# Generated by Django 5.1.4 on 2024-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_inscripcion_nombre_suplente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='max_inscripciones',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
