# Generated by Django 5.1.4 on 2024-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_alter_solicitudbaja_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='notificada_admin',
            field=models.BooleanField(default=False),
        ),
    ]
