# Generated by Django 5.1.4 on 2024-12-16 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_solicitudbaja_notificada_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscripcion',
            name='unique_user_turno',
        ),
        migrations.AddField(
            model_name='turno',
            name='es_completo_calculado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='max_inscripciones',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('dia', 'hora')},
        ),
    ]
