# Generated by Django 5.1.4 on 2024-12-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_remove_inscripcion_unique_user_turno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['dia', 'hora']},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='es_fijo',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='usuario_fijo',
        ),
    ]
