# Generated by Django 5.1.4 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='telefono_suplente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
