# Generated by Django 5.1.4 on 2024-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_inscripcion_telefono_suplente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='notificada_usuario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
    ]
