# Generated by Django 5.1.4 on 2024-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_solicitudbaja_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudbaja',
            name='notificada_admin',
        ),
        migrations.AlterField(
            model_name='solicitudbaja',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
