# Generated by Django 5.1.4 on 2024-12-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0012_remove_solicitudbaja_notificada_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='notificada_admin',
            field=models.BooleanField(default=False),
        ),
    ]
