# Generated by Django 5.1.4 on 2024-12-17 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0013_solicitudbaja_notificada_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='solicitudbaja',
            name='unique_solicitud_baja_per_inscripcion',
        ),
        migrations.AddField(
            model_name='solicitudbaja',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
