# Generated by Django 5.1.4 on 2024-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0014_remove_solicitudbaja_unique_solicitud_baja_per_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
